routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');
Route::get('/about', function () {
    return view('about');
})->name('about');
Route::get('/services', function () {
    return view('services');
})->name('services');
Route::get('/contact', function () {
    return view('contact');
})->name('contact');

Auth::routes();

Route::group(['middleware' => 'auth'], function () {
    Route::resource('/categories', 'CategoryController');
    Route::resource('/products', 'ProductController');
});
// Route::resource('/categories', 'CategoryController')->middleware('auth');
// Route::resource('/products', 'ProductController')->middleware('auth');

resources/views/about.blade.php
@extends('master')

@section('content')
<div class="px-0 col-lg-12">
    <h1 class="my-4">About Us</h1>
    <p>Selamat Datang di halaman About</p>
</div>
@endsection

resources/views/contact.blade.php
@extends('master')

@section('content')
<div class="px-0 col-lg-12">
    <h1 class="my-4">Contact</h1>
    <p>Selamat Datang di halaman Contact</p>
</div>
@endsection

resources/views/home.blade.php
@extends('master')

@section('content')
<div class="d-flex">
    <div class="px-0 col-md-3">
        <h3 class="my-4">Category</h3>
        <div class="list-group">
            @forelse($categories as $category)
            <a href="/?category_id={{ $category->id }}" class="list-group-item">{{ $category->name }}</a>
            @empty
            <p>No Category</p>
            @endforelse
        </div>
    </div>
    <div class="ml-4 col-md-9">
        <div id="carouselExampleIndicators" class="my-4 carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner" role="listbox">
                <div class="carousel-item active">
                    <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="First slide">
                </div>
                <div class="carousel-item">
                    <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Second slide">
                </div>
                <div class="carousel-item">
                    <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Third slide">
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>

        <div class="row">

            @forelse ($products as $product)
            <div class="mb-4 col-lg-4 col-md-6">
                <div class="card h-100">
                    <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
                    <div class="card-body">
                        <h4 class="card-title">
                            <a href="#">{{ $product->name }}</a>
                        </h4>
                        <h5>${{ $product->price }}</h5>
                        <p class="card-text">{{ $product->description }}</p>
                        <hr>
                        <small>
                            Category : {{ ($product->category->name) ?? "No Category" }}
                        </small>
                    </div>
                    <div class="card-footer">
                        <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                    </div>
                </div>
            </div>
            @empty
            <p>No Product</p>
            @endforelse

        </div>
        <!-- /.row -->
    </div>
</div>
@endsection

resources/views/master.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Larashop 7</title>

    <!-- Bootstrap core CSS -->
    <link href="{{ asset('vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{{ asset('css/shop-homepage.css') }}" rel="stylesheet">

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="#">Start Bootstrap</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="ml-auto navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" href="{{ route('home') }}">Home
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('about') }}">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('services') }}">Services</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('contact') }}">Contact</a>
                    </li>

                    @guest
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('login') }}">Login</a>
                    </li>
                    @endguest

                    @auth
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('categories.index') }}">Categories</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('products.index') }}">Products</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#"
                            onclick="document.getElementById('logout-form').submit()">Logout</a>
                        <form action="{{ route('logout') }}" method="post" id="logout-form">
                            @csrf
                        </form>
                    </li>
                    @endauth

                </ul>
            </div>
        </div>
    </nav>

    <!-- Page Content -->
    <div class="wrapper">
        <div class="px-0 py-4 wrapper__container">
            <div class="row">
                <div class="container">

                    @yield('content')

                </div>
            </div>
            <!-- /.row -->
        </div>
        <!-- /.wrapper__container -->

        <!-- Footer -->
        <footer class="py-4 wrapper_footer bg-dark">
            <div class="container">
                <p class="m-0 text-center text-white">Copyright &copy; Your Website 2020</p>
            </div>
            <!-- /.container -->
        </footer>
    </div>

    @include('sweetalert::alert')
    <!-- Bootstrap core JavaScript -->
    <script src="{{ asset('vendor/jquery/jquery.min.js') }}"></script>
    <script src="{{ asset('vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

</body>

</html>

resources/views/services.blade.php
@extends('master')

@section('content')
<div class="px-0 col-lg-12">
    <h1 class="my-4">Services</h1>
    <p>Selamat Datang di halaman Services</p>
</div>
@endsection