routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');
Route::get('/about', function () {
    return view('about');
})->name('about');
Route::get('/services', function () {
    return view('services');
})->name('services');
Route::get('/contact', function () {
    return view('contact');
})->name('contact');

Auth::routes();

Route::group(['middleware' => 'auth'], function () {
    Route::resource('/categories', 'CategoryController');
    Route::resource('/products', 'ProductController');
});
// Route::resource('/categories', 'CategoryController')->middleware('auth');
// Route::resource('/products', 'ProductController')->middleware('auth');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = ['name', 'price', 'description', 'photo', 'category_id'];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreProductRequest;
use App\Product;
use App\Category;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @retFurn \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::all();
        $categories = Category::all();

        return view('products.index', compact('products', 'categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('products.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreProductRequest $request)
    {
        $photo = $request->file('photo', '')->store('products/photos', 'public');

        Product::create([
            'name' => $request->name,
            'description' => $request->description,
            'price' => $request->price,
            'category_id' => $request->category_id,
            'photo' => $photo,
       ]);

        toast('Your Product has been saved', 'success');

        return redirect()->route('products.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product = Product::findOrFail($id);

        return view('products.show', compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::findOrFail($id);
        $categories = Category::all();

        return view('products.edit', compact('product', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreProductRequest $request, $id)
    {
        $product = Product::findOrFail($id);

        $product->name = $request->name;
        $product->description = $request->description;
        $product->category_id = $request->category_id;
        $product->price = $request->price;

        if ($request->hasfile('photo')) {
            if ($product->photo && file_exists(storage_path('app/public/'.$product->photo))) {
                \Storage::delete('public/'.$product->photo);
            }

            $photo = $request->file('photo')->store('products/photos', 'public');

            $product->photo = $photo;
        }

        $product->save();

        toast('Your Product has been updated', 'success');

        return redirect()->route('products.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = Product::findOrFail($id);
        $product->delete();

        toast('Your product has been deleted', 'success');

        return redirect()->route('products.index');
    }
}

resources/views/products/create.blade.php
@extends('master')

@section('content')
{{-- {{ dd($categories) }} --}}
<div class="px-0 col-lg-12">
    <h1 class="my-4">New Categories</h1>

    <form action={{ route('products.store') }} method="post" enctype="multipart/form-data">
        @csrf

        <div class="form-group">
            <label for="name">Product Name</label>
            <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" id="name"
                value="{{ old('name') }}">
            @error('name')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="form-group">
            <label for="description">Product Description</label>
            <textarea name="description" id="description" class="form-control">{{ old('description') }}</textarea>
        </div>
        <div class="form-group">
            <label for="price">Product Price ($)</label>
            <input type="text" name="price" class="form-control @error('price')
                is-invalid
            @enderror" id="price" value="{{ old('price') }}">
            @error('price')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="form-group">
            <label for="category_id">Product Category</label>
            <select name="category_id" id="category_id" class="form-control">
                @forelse($categories as $category)
                <option value="{{ $category->id }}">{{ $category->name }}</option>
                @empty
                <option value="0">No Category Product</option>
                @endforelse
            </select>
        </div>
        <div class="form-group">
            <label for="photo">Product Photo</label>
            <input type="file" name="photo" id="photo" class="form-control-file" />
        </div>
        <input type="submit" value="Save" class="px-4 py-1 btn btn-primary btn-sm" />
    </form>

</div>
@endsection

resources/views/products/edit.blade.php
@extends('master')

@section('content')
{{-- {{ dd($categories) }} --}}
<div class="px-0 col-lg-12">
    <h1 class="my-4">Update Product</h1>

    <form action={{ route('products.update', $product->id) }} method="post" enctype="multipart/form-data">
        @csrf
        @method('put')

        <div class="form-group">
            <label for="name">Product Name</label>
            <input type="text" name="name" class="form-control" id="name" value="{{ $product->name }}">
        </div>
        <div class="form-group">
            <label for="description">Product Description</label>
            <textarea name="description" id="description" class="form-control">{{ $product->description }}</textarea>
        </div>
        <div class="form-group">
            <label for="price">Product Price ($)</label>
            <input type="text" name="price" class="form-control" id="price" value="{{ $product->price }}">
        </div>
        <div class="form-group">
            <label for="category_id">Product Category</label>
            <select name="category_id" id="category_id" class="form-control">
                @forelse($categories as $category)
                <option value="{{ $category->id }}" @if ($category->id == $product->category_id) selected
                    @endif>{{ $category->name }}</option>
                @empty
                <option value="0">No Category Product</option>
                @endforelse
            </select>
        </div>
        <div class="form-group">
            <label for="photo">Product Photo</label>
            @if ($product->photo)
            <br />
            <span class="px-4 py-2 mb-2 badge badge-primary">Current Photo</span>
            <br />
            <img src="{{ asset('storage/'.$product->photo) }}" alt="{{ $product->photo }}" width="100" />
            <br />
            @else
            <br />
            <span class="px-4 py-2 mb-2 badge badge-danger">No Photo Profile</span>
            @endif
            <input type="file" name="photo" id="photo" class="form-control" />
            <small class="text-danger">Kosongkan jika tidak ingin merubah photo profile</small>
        </div>
        <input type="submit" value="Update" class="px-4 py-1 btn btn-primary btn-sm" />
    </form>

</div>
@endsection

resources/views/products/index.blade.php
@extends('master')

@section('content')
{{-- {{ dd($categories) }} --}}
<div class="px-0 col-lg-12">
    <h1 class="my-4">Products</h1>
    <a href="{{ route('products.create')}}" class="px-4 py-1 mb-2 btn btn-primary btn-sm">New Product</a>
    <table class="table">
        <thead class=" thead-dark">
            <tr>
                <th>No</th>
                <th>Name</th>
                <th>Category</th>
                <th>Price</th>
                <th>Description</th>
                <th class="text-right">Action</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($products as $product)
            <tr>
                <td>{{ $loop->iteration }}</td>
                <td>{{ $product->name }}</td>
                <td>{{ ($product->category->name) ?? 'No Category' }}</td>
                <td>${{ $product->price }}</td>
                <td>{{ $product->description }}</td>
                <td class="text-right">
                    <a href="{{ route('products.show', $product->id)}}" class="btn btn-primary btn-sm">Show</a>
                    <a href="{{ route('products.edit', $product->id)}}" class="btn btn-info btn-sm">Edit</a>
                    <form action="{{ route('products.destroy', $product->id) }}" method="post" class="d-inline">
                        @csrf
                        @method('delete')
                        <input type="submit" value="delete" class="btn btn-danger btn-sm"
                            onclick="return confirm('Are you sure you want to delete this products ?')" />
                    </form>

                </td>
            </tr>
            @empty
            <tr>
                <td colspan="3">No Categories</td>
            </tr>
            @endforelse
        </tbody>
    </table>
</div>
@endsection

resources/views/products/show.blade.php
@extends('master')

@section('content')
{{-- {{ dd($categories) }} --}}
<div class="px-0 col-lg-12">
    <h1 class="my-4">Detail Product</h1>

    <table class="table">
        <tbody>
            <tr>
                <td>Product ID</td>
                <td>:</td>
                <td>{{ $product->id }}</td>
            </tr>
            <tr>
                <td>Product Name</td>
                <td>:</td>
                <td>{{ $product->name }}</td>
            </tr>
            <tr>
                <td>Product Description</td>
                <td>:</td>
                <td>{{ $product->description }}</td>
            </tr>
            <tr>
                <td>Product Category</td>
                <td>:</td>
                <td>{{ $product->category->name }}</td>
            </tr>
            <tr>
                <td>Product Price</td>
                <td>:</td>
                <td>{{ $product->price }}</td>
            </tr>
            <tr>
                <td>Product Image</td>
                <td>:</td>
                <td><img src="{{ asset($product->photo) }}" alt="{{ $product->name}}" width="500px" /></td>
            </tr>
            <tr>
                <td>Created At</td>
                <td>:</td>
                <td>{{ $product->created_at }}</td>
            </tr>
            <tr>
                <td>Updated At</td>
                <td>:</td>
                <td>{{ $product->updated_at }}</td>
            </tr>
        </tbody>
    </table>

</div>
@endsection